import type { LanguageCode } from "@aion-timetable/shared";

export interface UiStrings {
  settingsTitle: string;
  settingsClose: string;
  settingsLanguage: string;
  settingsMyLevel: string;
  settingsMyLevelPlaceholder: string;
  settingsFontSize: string;
  dragHandle: string;
  updateBanner: string;
  pagerNow: string;
  pagerFull: string;
  teamStartTab: string;
  teamJoinTab: string;
  teamNamePlaceholder: string;
  teamDescriptionPlaceholder: string;
  teamPasswordPlaceholder: string;
  teamInviteCodePlaceholder: string;
  teamDisplayNamePlaceholder: string;
  teamCreateButton: string;
  teamJoinButton: string;
  teamCreateError: string;
  teamJoinError: string;
  teamInviteCodeLabel: string;
  teamLeaveButton: string;
  teamOwnerTag: string;
  commentPlaceholder: string;
  commentSend: string;
  killButton: string;
  upcomingEmpty: string;
  scheduleEmpty: string;
  scheduleServerSuffix: string;
  scheduleLocalSuffix: string;
  respawnExpected: string;
  upcomingRunning: string;
  riftFromToTemplate: string;
}

const EN: UiStrings = {
  settingsTitle: "Display",
  settingsClose: "Close",
  settingsLanguage: "Language",
  settingsMyLevel: "My level",
  settingsMyLevelPlaceholder: "e.g. 65",
  settingsFontSize: "Font size",
  dragHandle: "⠿ Move (Ctrl+Shift+O to exit)",
  updateBanner: "Installing update, restarting shortly…",
  pagerNow: "‹ Now/Soon",
  pagerFull: "Full schedule ›",
  teamStartTab: "Start team",
  teamJoinTab: "Join team",
  teamNamePlaceholder: "Team name",
  teamDescriptionPlaceholder: "Description",
  teamPasswordPlaceholder: "Password",
  teamInviteCodePlaceholder: "Invite code",
  teamDisplayNamePlaceholder: "Your display name",
  teamCreateButton: "Create team",
  teamJoinButton: "Join",
  teamCreateError: "Could not create the team.",
  teamJoinError: "Failed to join.",
  teamInviteCodeLabel: "Invite code:",
  teamLeaveButton: "Leave team",
  teamOwnerTag: "(Owner)",
  commentPlaceholder: "Comment...",
  commentSend: "Send",
  killButton: "Kill",
  upcomingEmpty: "Nothing coming up in the next hour.",
  scheduleEmpty: "No events found.",
  scheduleServerSuffix: "server",
  scheduleLocalSuffix: "local",
  respawnExpected: "expected",
  upcomingRunning: "running",
  riftFromToTemplate: "from {from} to {to}",
};

const DE: UiStrings = {
  settingsTitle: "Darstellung",
  settingsClose: "Schließen",
  settingsLanguage: "Sprache",
  settingsMyLevel: "Mein Level",
  settingsMyLevelPlaceholder: "z. B. 65",
  settingsFontSize: "Schriftgröße",
  dragHandle: "⠿ Verschieben (Strg+Umschalt+O zum Verlassen)",
  updateBanner: "Update wird installiert, App startet gleich neu…",
  pagerNow: "‹ Jetzt/Bald",
  pagerFull: "Ganzer Plan ›",
  teamStartTab: "Team starten",
  teamJoinTab: "Team beitreten",
  teamNamePlaceholder: "Team-Name",
  teamDescriptionPlaceholder: "Beschreibung",
  teamPasswordPlaceholder: "Passwort",
  teamInviteCodePlaceholder: "Einladungscode",
  teamDisplayNamePlaceholder: "Dein Anzeigename",
  teamCreateButton: "Team erstellen",
  teamJoinButton: "Beitreten",
  teamCreateError: "Team konnte nicht erstellt werden.",
  teamJoinError: "Beitritt fehlgeschlagen.",
  teamInviteCodeLabel: "Einladungscode:",
  teamLeaveButton: "Team verlassen",
  teamOwnerTag: "(Besitzer)",
  commentPlaceholder: "Kommentar...",
  commentSend: "Senden",
  killButton: "Getötet",
  upcomingEmpty: "Nichts in der nächsten Stunde.",
  scheduleEmpty: "Keine Termine gefunden.",
  scheduleServerSuffix: "Server",
  scheduleLocalSuffix: "lokal",
  respawnExpected: "erwartet",
  upcomingRunning: "läuft",
  riftFromToTemplate: "von {from} nach {to}",
};

const ES: UiStrings = {
  settingsTitle: "Apariencia",
  settingsClose: "Cerrar",
  settingsLanguage: "Idioma",
  settingsMyLevel: "Mi nivel",
  settingsMyLevelPlaceholder: "p. ej. 65",
  settingsFontSize: "Tamaño de fuente",
  dragHandle: "⠿ Mover (Ctrl+Shift+O para salir)",
  updateBanner: "Instalando actualización, la app se reiniciará enseguida…",
  pagerNow: "‹ Ahora/Pronto",
  pagerFull: "Horario completo ›",
  teamStartTab: "Crear equipo",
  teamJoinTab: "Unirse a un equipo",
  teamNamePlaceholder: "Nombre del equipo",
  teamDescriptionPlaceholder: "Descripción",
  teamPasswordPlaceholder: "Contraseña",
  teamInviteCodePlaceholder: "Código de invitación",
  teamDisplayNamePlaceholder: "Tu nombre visible",
  teamCreateButton: "Crear equipo",
  teamJoinButton: "Unirse",
  teamCreateError: "No se pudo crear el equipo.",
  teamJoinError: "No se pudo unir al equipo.",
  teamInviteCodeLabel: "Código de invitación:",
  teamLeaveButton: "Abandonar equipo",
  teamOwnerTag: "(Propietario)",
  commentPlaceholder: "Comentario...",
  commentSend: "Enviar",
  killButton: "Muerto",
  upcomingEmpty: "Nada en la próxima hora.",
  scheduleEmpty: "No se encontraron eventos.",
  scheduleServerSuffix: "servidor",
  scheduleLocalSuffix: "local",
  respawnExpected: "esperado",
  upcomingRunning: "en curso",
  riftFromToTemplate: "de {from} a {to}",
};

const IT: UiStrings = {
  settingsTitle: "Aspetto",
  settingsClose: "Chiudi",
  settingsLanguage: "Lingua",
  settingsMyLevel: "Il mio livello",
  settingsMyLevelPlaceholder: "es. 65",
  settingsFontSize: "Dimensione carattere",
  dragHandle: "⠿ Sposta (Ctrl+Shift+O per uscire)",
  updateBanner: "Installazione aggiornamento, l'app si riavvierà a breve…",
  pagerNow: "‹ Ora/Presto",
  pagerFull: "Programma completo ›",
  teamStartTab: "Crea team",
  teamJoinTab: "Unisciti al team",
  teamNamePlaceholder: "Nome del team",
  teamDescriptionPlaceholder: "Descrizione",
  teamPasswordPlaceholder: "Password",
  teamInviteCodePlaceholder: "Codice di invito",
  teamDisplayNamePlaceholder: "Il tuo nome visualizzato",
  teamCreateButton: "Crea team",
  teamJoinButton: "Unisciti",
  teamCreateError: "Impossibile creare il team.",
  teamJoinError: "Impossibile unirsi al team.",
  teamInviteCodeLabel: "Codice di invito:",
  teamLeaveButton: "Abbandona il team",
  teamOwnerTag: "(Proprietario)",
  commentPlaceholder: "Commento...",
  commentSend: "Invia",
  killButton: "Ucciso",
  upcomingEmpty: "Niente nella prossima ora.",
  scheduleEmpty: "Nessun evento trovato.",
  scheduleServerSuffix: "server",
  scheduleLocalSuffix: "locale",
  respawnExpected: "previsto",
  upcomingRunning: "in corso",
  riftFromToTemplate: "da {from} a {to}",
};

const FR: UiStrings = {
  settingsTitle: "Apparence",
  settingsClose: "Fermer",
  settingsLanguage: "Langue",
  settingsMyLevel: "Mon niveau",
  settingsMyLevelPlaceholder: "p. ex. 65",
  settingsFontSize: "Taille de police",
  dragHandle: "⠿ Déplacer (Ctrl+Shift+O pour quitter)",
  updateBanner: "Installation de la mise à jour, redémarrage imminent…",
  pagerNow: "‹ Maintenant/Bientôt",
  pagerFull: "Planning complet ›",
  teamStartTab: "Créer une équipe",
  teamJoinTab: "Rejoindre une équipe",
  teamNamePlaceholder: "Nom de l'équipe",
  teamDescriptionPlaceholder: "Description",
  teamPasswordPlaceholder: "Mot de passe",
  teamInviteCodePlaceholder: "Code d'invitation",
  teamDisplayNamePlaceholder: "Ton nom affiché",
  teamCreateButton: "Créer l'équipe",
  teamJoinButton: "Rejoindre",
  teamCreateError: "Impossible de créer l'équipe.",
  teamJoinError: "Échec de la connexion à l'équipe.",
  teamInviteCodeLabel: "Code d'invitation :",
  teamLeaveButton: "Quitter l'équipe",
  teamOwnerTag: "(Propriétaire)",
  commentPlaceholder: "Commentaire...",
  commentSend: "Envoyer",
  killButton: "Tué",
  upcomingEmpty: "Rien dans la prochaine heure.",
  scheduleEmpty: "Aucun événement trouvé.",
  scheduleServerSuffix: "serveur",
  scheduleLocalSuffix: "local",
  respawnExpected: "prévu",
  upcomingRunning: "en cours",
  riftFromToTemplate: "de {from} à {to}",
};

const TR: UiStrings = {
  settingsTitle: "Görünüm",
  settingsClose: "Kapat",
  settingsLanguage: "Dil",
  settingsMyLevel: "Seviyem",
  settingsMyLevelPlaceholder: "örn. 65",
  settingsFontSize: "Yazı boyutu",
  dragHandle: "⠿ Taşı (çıkmak için Ctrl+Shift+O)",
  updateBanner: "Güncelleme yükleniyor, uygulama kısa süre içinde yeniden başlayacak…",
  pagerNow: "‹ Şimdi/Yakında",
  pagerFull: "Tüm program ›",
  teamStartTab: "Takım kur",
  teamJoinTab: "Takıma katıl",
  teamNamePlaceholder: "Takım adı",
  teamDescriptionPlaceholder: "Açıklama",
  teamPasswordPlaceholder: "Şifre",
  teamInviteCodePlaceholder: "Davet kodu",
  teamDisplayNamePlaceholder: "Görünen adın",
  teamCreateButton: "Takım oluştur",
  teamJoinButton: "Katıl",
  teamCreateError: "Takım oluşturulamadı.",
  teamJoinError: "Takıma katılma başarısız oldu.",
  teamInviteCodeLabel: "Davet kodu:",
  teamLeaveButton: "Takımdan ayrıl",
  teamOwnerTag: "(Sahip)",
  commentPlaceholder: "Yorum...",
  commentSend: "Gönder",
  killButton: "Öldürüldü",
  upcomingEmpty: "Önümüzdeki bir saat içinde bir şey yok.",
  scheduleEmpty: "Etkinlik bulunamadı.",
  scheduleServerSuffix: "sunucu",
  scheduleLocalSuffix: "yerel",
  respawnExpected: "beklenen",
  upcomingRunning: "devam ediyor",
  riftFromToTemplate: "{from}'dan {to}'ye",
};

const RU: UiStrings = {
  settingsTitle: "Отображение",
  settingsClose: "Закрыть",
  settingsLanguage: "Язык",
  settingsMyLevel: "Мой уровень",
  settingsMyLevelPlaceholder: "напр. 65",
  settingsFontSize: "Размер шрифта",
  dragHandle: "⠿ Переместить (Ctrl+Shift+O для выхода)",
  updateBanner: "Установка обновления, приложение скоро перезапустится…",
  pagerNow: "‹ Сейчас/Скоро",
  pagerFull: "Весь план ›",
  teamStartTab: "Создать команду",
  teamJoinTab: "Присоединиться",
  teamNamePlaceholder: "Название команды",
  teamDescriptionPlaceholder: "Описание",
  teamPasswordPlaceholder: "Пароль",
  teamInviteCodePlaceholder: "Код приглашения",
  teamDisplayNamePlaceholder: "Твоё отображаемое имя",
  teamCreateButton: "Создать команду",
  teamJoinButton: "Присоединиться",
  teamCreateError: "Не удалось создать команду.",
  teamJoinError: "Не удалось присоединиться.",
  teamInviteCodeLabel: "Код приглашения:",
  teamLeaveButton: "Покинуть команду",
  teamOwnerTag: "(Владелец)",
  commentPlaceholder: "Комментарий...",
  commentSend: "Отправить",
  killButton: "Убит",
  upcomingEmpty: "В ближайший час ничего нет.",
  scheduleEmpty: "События не найдены.",
  scheduleServerSuffix: "сервер",
  scheduleLocalSuffix: "локальное",
  respawnExpected: "ожидается",
  upcomingRunning: "идёт сейчас",
  riftFromToTemplate: "из {from} в {to}",
};

const PL: UiStrings = {
  settingsTitle: "Wygląd",
  settingsClose: "Zamknij",
  settingsLanguage: "Język",
  settingsMyLevel: "Mój poziom",
  settingsMyLevelPlaceholder: "np. 65",
  settingsFontSize: "Rozmiar czcionki",
  dragHandle: "⠿ Przesuń (Ctrl+Shift+O, aby wyjść)",
  updateBanner: "Instalowanie aktualizacji, aplikacja zaraz się zrestartuje…",
  pagerNow: "‹ Teraz/Wkrótce",
  pagerFull: "Pełny harmonogram ›",
  teamStartTab: "Utwórz zespół",
  teamJoinTab: "Dołącz do zespołu",
  teamNamePlaceholder: "Nazwa zespołu",
  teamDescriptionPlaceholder: "Opis",
  teamPasswordPlaceholder: "Hasło",
  teamInviteCodePlaceholder: "Kod zaproszenia",
  teamDisplayNamePlaceholder: "Twoja wyświetlana nazwa",
  teamCreateButton: "Utwórz zespół",
  teamJoinButton: "Dołącz",
  teamCreateError: "Nie udało się utworzyć zespołu.",
  teamJoinError: "Nie udało się dołączyć.",
  teamInviteCodeLabel: "Kod zaproszenia:",
  teamLeaveButton: "Opuść zespół",
  teamOwnerTag: "(Właściciel)",
  commentPlaceholder: "Komentarz...",
  commentSend: "Wyślij",
  killButton: "Zabity",
  upcomingEmpty: "Nic w ciągu najbliższej godziny.",
  scheduleEmpty: "Nie znaleziono wydarzeń.",
  scheduleServerSuffix: "serwer",
  scheduleLocalSuffix: "lokalny",
  respawnExpected: "oczekiwane",
  upcomingRunning: "trwa",
  riftFromToTemplate: "z {from} do {to}",
};

const ZH: UiStrings = {
  settingsTitle: "显示",
  settingsClose: "关闭",
  settingsLanguage: "语言",
  settingsMyLevel: "我的等级",
  settingsMyLevelPlaceholder: "例如 65",
  settingsFontSize: "字体大小",
  dragHandle: "⠿ 移动(按 Ctrl+Shift+O 退出)",
  updateBanner: "正在安装更新,应用即将重启…",
  pagerNow: "‹ 现在/即将",
  pagerFull: "完整日程 ›",
  teamStartTab: "创建团队",
  teamJoinTab: "加入团队",
  teamNamePlaceholder: "团队名称",
  teamDescriptionPlaceholder: "描述",
  teamPasswordPlaceholder: "密码",
  teamInviteCodePlaceholder: "邀请码",
  teamDisplayNamePlaceholder: "你的显示名称",
  teamCreateButton: "创建团队",
  teamJoinButton: "加入",
  teamCreateError: "无法创建团队。",
  teamJoinError: "加入失败。",
  teamInviteCodeLabel: "邀请码:",
  teamLeaveButton: "离开团队",
  teamOwnerTag: "(团队所有者)",
  commentPlaceholder: "评论...",
  commentSend: "发送",
  killButton: "已击杀",
  upcomingEmpty: "接下来一小时内没有安排。",
  scheduleEmpty: "未找到日程。",
  scheduleServerSuffix: "服务器",
  scheduleLocalSuffix: "本地",
  respawnExpected: "预计",
  upcomingRunning: "进行中",
  riftFromToTemplate: "从 {from} 到 {to}",
};

const STRINGS: Record<LanguageCode, UiStrings> = {
  en: EN,
  de: DE,
  es: ES,
  it: IT,
  fr: FR,
  tr: TR,
  ru: RU,
  pl: PL,
  zh: ZH,
};

export function t(language: LanguageCode): UiStrings {
  return STRINGS[language] ?? EN;
}
